/* SentinelForge console: API data is rendered with textContent only. */
(function () {
  "use strict";
  const state = { data: { runs: [], alerts: [], incidents: [], investigations: [] }, page: "overview" };
  const $ = (id) => document.getElementById(id);
  const esc = (value) => value == null ? "—" : String(value);
  const date = (value) => value ? new Date(value).toLocaleString() : "—";
  const jsonText = (value) => JSON.stringify(value, null, 2);
  const severity = (value) => `<span class="badge ${esc(value)}">${esc(value)}</span>`;
  const status = (value) => `<span class="badge status">${esc(value)}</span>`;
  function node(tag, text, className) { const el = document.createElement(tag); if (className) el.className = className; if (text != null) el.textContent = text; return el; }
  function safeFragment(markup) { const template = document.createElement("template"); template.innerHTML = markup; return template.content; }
  async function request(path, options) {
    let response;
    try { response = await fetch(path, options); } catch (error) { throw new Error("API unavailable. Start `python -m sentinelforge serve` and refresh."); }
    let body;
    try { body = await response.json(); } catch (error) { throw new Error("The API returned invalid JSON."); }
    if (!response.ok) throw new Error(body && body.error ? body.error : `API request failed (${response.status}).`);
    return body;
  }
  const api = { health: () => request("/health"), runs: (limit) => request(`/runs${limit ? `?limit=${limit}` : ""}`), alerts: (severityValue) => request(`/alerts${severityValue ? `?severity=${encodeURIComponent(severityValue)}` : ""}`), incidents: (severityValue) => request(`/incidents${severityValue ? `?severity=${encodeURIComponent(severityValue)}` : ""}`), investigations: () => request("/investigations"), detail: (resource, id) => request(`/${resource}/${encodeURIComponent(id)}`), analyze: (body) => request("/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }) };
  function showMessage(message) { $("global-message").textContent = message; $("global-message").classList.remove("hidden"); }
  function clearMessage() { $("global-message").classList.add("hidden"); }
  async function load() {
    try {
      const [health, runs, alerts, incidents, investigations] = await Promise.all([api.health(), api.runs(20), api.alerts(), api.incidents(), api.investigations()]);
      $("api-status").textContent = "API reachable"; $("api-status").className = "status-dot available";
      state.data = { runs, alerts, incidents, investigations }; clearMessage(); renderAll();
    } catch (error) { $("api-status").textContent = "API unavailable"; $("api-status").className = "status-dot unavailable"; showMessage(error.message); renderAll(); }
  }
  function renderAll() { renderOverview(); renderAlerts(); renderIncidents(); renderInvestigations(); renderRuns(); }
  function renderOverview() {
    const { alerts, incidents, investigations, runs } = state.data;
    const risks = incidents.map((item) => item.risk_assessment).filter(Boolean); const highest = risks.reduce((best, item) => !best || item.score > best.score ? item : best, null);
    $("summary-cards").replaceChildren(...[["Total alerts", alerts.length, "Persisted detections"], ["Incidents", incidents.length, "Correlated activity"], ["Active investigations", investigations.filter((i) => i.status === "active").length, "Open analyst context"], ["Highest risk", highest ? `${highest.score} · ${highest.level}` : "None", "Transparent prioritization"]].map((item) => { const card = node("div", null, "metric"); card.append(node("div", item[0], "metric-label"), node("div", item[1], "metric-value"), node("div", item[2], "metric-sub")); return card; }));
    renderAlertRows($("overview-alerts"), alerts.slice(-5).reverse(), true); renderIncidentRows($("overview-incidents"), incidents.slice(-5).reverse(), true); renderRunRows($("overview-runs"), runs.slice(-5).reverse(), true);
    const counts = ["low", "medium", "high", "critical"].map((level) => [level, alerts.filter((a) => a.severity === level).length]); const max = Math.max(1, ...counts.map((item) => item[1])); $("severity-chart").replaceChildren(...counts.map(([level, count]) => { const row = node("div", null, "dist-row"); row.append(node("span", level), Object.assign(node("div", null, "bar"), { innerHTML: `<i style="width:${count / max * 100}%"></i>` }), node("strong", count)); return row; }));
  }
  function renderAlertRows(container, rows, compact) { if (!rows.length) { container.replaceChildren(node("div", "No alerts available.", "empty")); return; } const table = node("table", null, "data-table"); table.innerHTML = `<thead><tr><th>Severity</th><th>Rule</th><th>Title</th><th>Timestamp</th>${compact ? "" : "<th>Evidence</th>"}</tr></thead>`; const body = node("tbody"); rows.forEach((item) => { const tr = node("tr"); tr.append(node("td", null), node("td", item.rule_id, "mono id"), node("td", item.title), node("td", date(item.timestamp), "muted")); tr.firstChild.append(...safeFragment(severity(item.severity))); if (!compact) tr.append(node("td", item.evidence ? item.evidence.length : 0)); tr.addEventListener("click", () => detail("alerts", item.alert_id)); body.append(tr); }); table.append(body); container.replaceChildren(table); }
  function renderIncidentRows(container, rows, compact) { if (!rows.length) { container.replaceChildren(node("div", "No incidents available.", "empty")); return; } const table = node("table", null, "data-table"); table.innerHTML = `<thead><tr><th>Severity</th><th>Title</th><th>Risk</th><th>Status</th><th>Updated</th></tr></thead>`; const body = node("tbody"); rows.forEach((item) => { const tr = node("tr"); const risk = item.risk_assessment; tr.append(node("td", null), node("td", item.title), node("td", risk ? `${risk.score} · ${risk.level}` : "—"), node("td", null), node("td", date(item.updated_at), "muted")); tr.firstChild.append(...safeFragment(severity(item.severity))); tr.children[3].append(...safeFragment(status(item.status))); tr.addEventListener("click", () => detail("incidents", item.incident_id)); body.append(tr); }); table.append(body); container.replaceChildren(table); }
  function renderRunRows(container, rows, compact) { if (!rows.length) { container.replaceChildren(node("div", "No analysis runs available.", "empty")); return; } const table = node("table", null, "data-table"); table.innerHTML = `<thead><tr><th>Timestamp</th><th>Source</th><th>Type</th><th>Events</th><th>Diagnostics</th></tr></thead>`; const body = node("tbody"); rows.forEach((item) => { const tr = node("tr"); tr.append(node("td", date(item.started_at), "muted"), node("td", item.source, "mono"), node("td", item.source_type), node("td", item.event_count), node("td", item.diagnostic_count)); tr.addEventListener("click", () => detail("runs", item.run_id)); body.append(tr); }); table.append(body); container.replaceChildren(table); }
  function renderAlerts() { const severityValue = $("alert-severity").value; const rule = $("alert-rule").value.toLowerCase(); renderAlertRows($("alerts-list"), state.data.alerts.filter((a) => (!severityValue || a.severity === severityValue) && (!rule || a.rule_id.toLowerCase().includes(rule))), false); }
  function renderIncidents() { const value = $("incident-severity").value; renderIncidentRows($("incidents-list"), state.data.incidents.filter((i) => !value || i.severity === value), false); }
  function renderInvestigations() { const rows = state.data.investigations; if (!rows.length) { $("investigations-list").replaceChildren(node("div", "No investigations available.", "empty")); return; } const table = node("table", null, "data-table"); table.innerHTML = "<thead><tr><th>Status</th><th>Investigation</th><th>Incident</th><th>Evidence</th><th>Timeline</th><th>Notes</th></tr></thead>"; const body = node("tbody"); rows.forEach((item) => { const tr = node("tr"); tr.append(node("td", null), node("td", item.investigation_id, "mono id"), node("td", item.incident_id, "mono id"), node("td", (item.evidence || []).length), node("td", (item.timeline || []).length), node("td", (item.analyst_notes || []).length)); tr.firstChild.append(...safeFragment(status(item.status))); tr.addEventListener("click", () => detail("investigations", item.investigation_id)); body.append(tr); }); table.append(body); $("investigations-list").replaceChildren(table); }
  function renderRuns() { renderRunRows($("runs-list"), state.data.runs, false); }
  function detail(resource, id) { api.detail(resource, id).then((item) => { $("detail-title").textContent = resource.slice(0, -1).toUpperCase() + " DETAILS"; const content = $("detail-content"); content.replaceChildren(); const heading = node("div", null, "detail-grid"); Object.entries(item).filter(([key]) => !["evidence", "timeline", "analyst_notes"].includes(key)).forEach(([key, value]) => { const box = node("div", null, "detail-item"); box.append(node("strong", key.replaceAll("_", " ")), node("span", typeof value === "object" ? jsonText(value) : esc(value), typeof value === "string" && value.length > 28 ? "mono" : "")); heading.append(box); }); content.append(heading); [["evidence", item.evidence], ["timeline", item.timeline], ["analyst_notes", item.analyst_notes]].forEach(([key, values]) => { if (!values || !values.length) return; const section = node("section", null, "detail-section"); section.append(node("h3", key.replaceAll("_", " "))); values.forEach((value) => { const block = node("div", null, "evidence"); block.append(node("strong", value.summary || value.content || value.evidence_id || "Evidence")); const pre = node("pre", jsonText(value.event || value)); block.append(pre); section.append(block); }); content.append(section); }); $("detail-modal").classList.remove("hidden"); $("modal-close").focus(); }).catch((error) => showMessage(error.message)); }
  function showPage(page) { state.page = page; document.querySelectorAll(".page").forEach((el) => el.classList.toggle("active", el.id === `page-${page}`)); document.querySelectorAll(".nav-item").forEach((el) => el.classList.toggle("active", el.dataset.page === page)); $("main").focus(); }
  document.querySelectorAll(".nav-item,[data-page-link]").forEach((el) => el.addEventListener("click", () => showPage(el.dataset.page || el.dataset.pageLink)));
  $("refresh-btn").addEventListener("click", load); $("alert-severity").addEventListener("change", renderAlerts); $("alert-rule").addEventListener("input", renderAlerts); $("incident-severity").addEventListener("change", renderIncidents); $("modal-close").addEventListener("click", () => $("detail-modal").classList.add("hidden")); $("detail-modal").addEventListener("click", (event) => { if (event.target === $("detail-modal")) $("detail-modal").classList.add("hidden"); }); document.addEventListener("keydown", (event) => { if (event.key === "Escape") $("detail-modal").classList.add("hidden"); }); $("analyze-form").addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.target); const body = {}; for (const [key, value] of form.entries()) if (value) body[key] = value; $("analyze-result").classList.remove("hidden"); $("analyze-result").textContent = "Running analysis…"; try { const result = await api.analyze(body); $("analyze-result").textContent = `Analysis complete: ${result.alerts.length} alerts, ${result.incidents.length} incidents, ${result.investigations.length} investigations.`; await load(); } catch (error) { $("analyze-result").textContent = error.message; } });
  load();
}());
